### ISSUE TITLE
Invalid/Deleted link under Blockchain

### ISSUE THREAD

**Issue by alaaltoros** [protofire/blockchain-learning-path#20]
The link under **Blockchain** > 1. [What is Blockchain?](https://medium.com/coinmonks/blockchain-technology-explained-7d68c4435aca) is no longer valid (the article was deleted by the author).

A suggested alternative (https://www.investopedia.com/terms/b/blockchain.asp)

**Comment by pablofullana** [comment]
Looks good to me. @alaaltoros do you mind creating a PR for this?

**Comment by alaaltoros** [comment]
I need permission for that

**Comment by soulhi9988** [comment]
Spam is going to work now
