### ISSUE TITLE
Storage on Eth blockchain

### ISSUE THREAD

**Issue by captain-woof** [protofire/blockchain-learning-path#31]
This article explained how Storage works in the eth blockchain, and I think it should be included in the list. It solved a lot of confusion for me, especially about which of the things are global and which are stored on blocks.

**[Getting Deep Into Ethereum: How Data Is Stored In Ethereum](https://hackernoon.com/getting-deep-into-ethereum-how-data-is-stored-in-ethereum-e3f669d96033)**

**Comment by pfmescher** [comment]
The article is no longer available. If you can find a cached version I would be happy to include it. I'll leave this issue open for a while

**Comment by pfmescher** [comment]
closing since enough time has passed without activity on this
