### ISSUE TITLE
Ethereum vs. Bitcoin link down

### ISSUE THREAD

**Issue by enzoferey** [protofire/blockchain-learning-path#34]
The blog post about "Features and differences between Bitcoin and Ethereum." pointing to https://vimba.co/blog/post/bitcoin-vs-ethereum is down.

I could find it (partially?) using the web archive => https://web.archive.org/web/20200929012506/https://vimba.co/blog/post/bitcoin-vs-ethereum. Still, we should probably look for a more up to date blog post that covers it ? Just update the link pointing to the web archive ?

**Comment by pfmescher** [comment]
Hi Enzo! Thanks for noticing this, I think one of the PRs I just merged addressed exactly this. Can you confirm if this issue remains relevant? If so a PR would be much appreciated

**Comment by enzoferey** [comment]
Looks good to me @pfmescher, closing issue 👍🏻
