### ISSUE TITLE
Second item link in Ethereum Theory has changed

### ISSUE THREAD

**Issue by averias** [protofire/blockchain-learning-path#51]
Hi,

The link on 
Ethereum > Theory > 2. Read this [article](https://blog.zeppelin.solutions/the-hitchhikers-guide-to-smart-contracts-in-ethereum-848f08001f05) on smart contracts development. (Est. time: 15 minutes)

has changed the domain and the new link is:
https://blog.openzeppelin.com/the-hitchhikers-guide-to-smart-contracts-in-ethereum-848f08001f05

**Comment by pfmescher** [comment]
Thanks! Fixed!
